# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from packet_pkg/PacketData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class PacketData(genpy.Message):
  _md5sum = "3537c672e01f284539612933c30ef10e"
  _type = "packet_pkg/PacketData"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

# 人脸识别数据
string face_name
float32 face_confidence
bool face_detected

# GPS数据
string utc_time
float64 latitude
float64 longitude
string lat_direction
string lon_direction
uint8 satellite_count
float32 altitude
float32 speed_kph
float32 heading_true
float32 heading_magnetic

# 系统状态
float32 cpu_usage
float32 memory_usage
uint32 frame_count

# 数据校验
uint32 checksum
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','face_name','face_confidence','face_detected','utc_time','latitude','longitude','lat_direction','lon_direction','satellite_count','altitude','speed_kph','heading_true','heading_magnetic','cpu_usage','memory_usage','frame_count','checksum']
  _slot_types = ['std_msgs/Header','string','float32','bool','string','float64','float64','string','string','uint8','float32','float32','float32','float32','float32','float32','uint32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,face_name,face_confidence,face_detected,utc_time,latitude,longitude,lat_direction,lon_direction,satellite_count,altitude,speed_kph,heading_true,heading_magnetic,cpu_usage,memory_usage,frame_count,checksum

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PacketData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.face_name is None:
        self.face_name = ''
      if self.face_confidence is None:
        self.face_confidence = 0.
      if self.face_detected is None:
        self.face_detected = False
      if self.utc_time is None:
        self.utc_time = ''
      if self.latitude is None:
        self.latitude = 0.
      if self.longitude is None:
        self.longitude = 0.
      if self.lat_direction is None:
        self.lat_direction = ''
      if self.lon_direction is None:
        self.lon_direction = ''
      if self.satellite_count is None:
        self.satellite_count = 0
      if self.altitude is None:
        self.altitude = 0.
      if self.speed_kph is None:
        self.speed_kph = 0.
      if self.heading_true is None:
        self.heading_true = 0.
      if self.heading_magnetic is None:
        self.heading_magnetic = 0.
      if self.cpu_usage is None:
        self.cpu_usage = 0.
      if self.memory_usage is None:
        self.memory_usage = 0.
      if self.frame_count is None:
        self.frame_count = 0
      if self.checksum is None:
        self.checksum = 0
    else:
      self.header = std_msgs.msg.Header()
      self.face_name = ''
      self.face_confidence = 0.
      self.face_detected = False
      self.utc_time = ''
      self.latitude = 0.
      self.longitude = 0.
      self.lat_direction = ''
      self.lon_direction = ''
      self.satellite_count = 0
      self.altitude = 0.
      self.speed_kph = 0.
      self.heading_true = 0.
      self.heading_magnetic = 0.
      self.cpu_usage = 0.
      self.memory_usage = 0.
      self.frame_count = 0
      self.checksum = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.face_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_fB().pack(_x.face_confidence, _x.face_detected))
      _x = self.utc_time
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2d().pack(_x.latitude, _x.longitude))
      _x = self.lat_direction
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.lon_direction
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B6f2I().pack(_x.satellite_count, _x.altitude, _x.speed_kph, _x.heading_true, _x.heading_magnetic, _x.cpu_usage, _x.memory_usage, _x.frame_count, _x.checksum))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.face_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.face_name = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.face_confidence, _x.face_detected,) = _get_struct_fB().unpack(str[start:end])
      self.face_detected = bool(self.face_detected)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.utc_time = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.utc_time = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.latitude, _x.longitude,) = _get_struct_2d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.lat_direction = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.lat_direction = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.lon_direction = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.lon_direction = str[start:end]
      _x = self
      start = end
      end += 33
      (_x.satellite_count, _x.altitude, _x.speed_kph, _x.heading_true, _x.heading_magnetic, _x.cpu_usage, _x.memory_usage, _x.frame_count, _x.checksum,) = _get_struct_B6f2I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.face_name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_fB().pack(_x.face_confidence, _x.face_detected))
      _x = self.utc_time
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2d().pack(_x.latitude, _x.longitude))
      _x = self.lat_direction
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.lon_direction
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B6f2I().pack(_x.satellite_count, _x.altitude, _x.speed_kph, _x.heading_true, _x.heading_magnetic, _x.cpu_usage, _x.memory_usage, _x.frame_count, _x.checksum))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.face_name = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.face_name = str[start:end]
      _x = self
      start = end
      end += 5
      (_x.face_confidence, _x.face_detected,) = _get_struct_fB().unpack(str[start:end])
      self.face_detected = bool(self.face_detected)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.utc_time = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.utc_time = str[start:end]
      _x = self
      start = end
      end += 16
      (_x.latitude, _x.longitude,) = _get_struct_2d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.lat_direction = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.lat_direction = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.lon_direction = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.lon_direction = str[start:end]
      _x = self
      start = end
      end += 33
      (_x.satellite_count, _x.altitude, _x.speed_kph, _x.heading_true, _x.heading_magnetic, _x.cpu_usage, _x.memory_usage, _x.frame_count, _x.checksum,) = _get_struct_B6f2I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2d = None
def _get_struct_2d():
    global _struct_2d
    if _struct_2d is None:
        _struct_2d = struct.Struct("<2d")
    return _struct_2d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B6f2I = None
def _get_struct_B6f2I():
    global _struct_B6f2I
    if _struct_B6f2I is None:
        _struct_B6f2I = struct.Struct("<B6f2I")
    return _struct_B6f2I
_struct_fB = None
def _get_struct_fB():
    global _struct_fB
    if _struct_fB is None:
        _struct_fB = struct.Struct("<fB")
    return _struct_fB
