// Generated by gencpp from file packet_pkg/PacketData.msg
// DO NOT EDIT!


#ifndef PACKET_PKG_MESSAGE_PACKETDATA_H
#define PACKET_PKG_MESSAGE_PACKETDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace packet_pkg
{
template <class ContainerAllocator>
struct PacketData_
{
  typedef PacketData_<ContainerAllocator> Type;

  PacketData_()
    : header()
    , face_name()
    , face_confidence(0.0)
    , face_detected(false)
    , utc_time()
    , latitude(0.0)
    , longitude(0.0)
    , lat_direction()
    , lon_direction()
    , satellite_count(0)
    , altitude(0.0)
    , speed_kph(0.0)
    , heading_true(0.0)
    , heading_magnetic(0.0)
    , cpu_usage(0.0)
    , memory_usage(0.0)
    , frame_count(0)
    , checksum(0)  {
    }
  PacketData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , face_name(_alloc)
    , face_confidence(0.0)
    , face_detected(false)
    , utc_time(_alloc)
    , latitude(0.0)
    , longitude(0.0)
    , lat_direction(_alloc)
    , lon_direction(_alloc)
    , satellite_count(0)
    , altitude(0.0)
    , speed_kph(0.0)
    , heading_true(0.0)
    , heading_magnetic(0.0)
    , cpu_usage(0.0)
    , memory_usage(0.0)
    , frame_count(0)
    , checksum(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _face_name_type;
  _face_name_type face_name;

   typedef float _face_confidence_type;
  _face_confidence_type face_confidence;

   typedef uint8_t _face_detected_type;
  _face_detected_type face_detected;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _utc_time_type;
  _utc_time_type utc_time;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _lat_direction_type;
  _lat_direction_type lat_direction;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _lon_direction_type;
  _lon_direction_type lon_direction;

   typedef uint8_t _satellite_count_type;
  _satellite_count_type satellite_count;

   typedef float _altitude_type;
  _altitude_type altitude;

   typedef float _speed_kph_type;
  _speed_kph_type speed_kph;

   typedef float _heading_true_type;
  _heading_true_type heading_true;

   typedef float _heading_magnetic_type;
  _heading_magnetic_type heading_magnetic;

   typedef float _cpu_usage_type;
  _cpu_usage_type cpu_usage;

   typedef float _memory_usage_type;
  _memory_usage_type memory_usage;

   typedef uint32_t _frame_count_type;
  _frame_count_type frame_count;

   typedef uint32_t _checksum_type;
  _checksum_type checksum;





  typedef boost::shared_ptr< ::packet_pkg::PacketData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::packet_pkg::PacketData_<ContainerAllocator> const> ConstPtr;

}; // struct PacketData_

typedef ::packet_pkg::PacketData_<std::allocator<void> > PacketData;

typedef boost::shared_ptr< ::packet_pkg::PacketData > PacketDataPtr;
typedef boost::shared_ptr< ::packet_pkg::PacketData const> PacketDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::packet_pkg::PacketData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::packet_pkg::PacketData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::packet_pkg::PacketData_<ContainerAllocator1> & lhs, const ::packet_pkg::PacketData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.face_name == rhs.face_name &&
    lhs.face_confidence == rhs.face_confidence &&
    lhs.face_detected == rhs.face_detected &&
    lhs.utc_time == rhs.utc_time &&
    lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.lat_direction == rhs.lat_direction &&
    lhs.lon_direction == rhs.lon_direction &&
    lhs.satellite_count == rhs.satellite_count &&
    lhs.altitude == rhs.altitude &&
    lhs.speed_kph == rhs.speed_kph &&
    lhs.heading_true == rhs.heading_true &&
    lhs.heading_magnetic == rhs.heading_magnetic &&
    lhs.cpu_usage == rhs.cpu_usage &&
    lhs.memory_usage == rhs.memory_usage &&
    lhs.frame_count == rhs.frame_count &&
    lhs.checksum == rhs.checksum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::packet_pkg::PacketData_<ContainerAllocator1> & lhs, const ::packet_pkg::PacketData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace packet_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::packet_pkg::PacketData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::packet_pkg::PacketData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::packet_pkg::PacketData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::packet_pkg::PacketData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::packet_pkg::PacketData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::packet_pkg::PacketData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::packet_pkg::PacketData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3537c672e01f284539612933c30ef10e";
  }

  static const char* value(const ::packet_pkg::PacketData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3537c672e01f2845ULL;
  static const uint64_t static_value2 = 0x39612933c30ef10eULL;
};

template<class ContainerAllocator>
struct DataType< ::packet_pkg::PacketData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "packet_pkg/PacketData";
  }

  static const char* value(const ::packet_pkg::PacketData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::packet_pkg::PacketData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# 人脸识别数据\n"
"string face_name\n"
"float32 face_confidence\n"
"bool face_detected\n"
"\n"
"# GPS数据\n"
"string utc_time\n"
"float64 latitude\n"
"float64 longitude\n"
"string lat_direction\n"
"string lon_direction\n"
"uint8 satellite_count\n"
"float32 altitude\n"
"float32 speed_kph\n"
"float32 heading_true\n"
"float32 heading_magnetic\n"
"\n"
"# 系统状态\n"
"float32 cpu_usage\n"
"float32 memory_usage\n"
"uint32 frame_count\n"
"\n"
"# 数据校验\n"
"uint32 checksum\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::packet_pkg::PacketData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::packet_pkg::PacketData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.face_name);
      stream.next(m.face_confidence);
      stream.next(m.face_detected);
      stream.next(m.utc_time);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.lat_direction);
      stream.next(m.lon_direction);
      stream.next(m.satellite_count);
      stream.next(m.altitude);
      stream.next(m.speed_kph);
      stream.next(m.heading_true);
      stream.next(m.heading_magnetic);
      stream.next(m.cpu_usage);
      stream.next(m.memory_usage);
      stream.next(m.frame_count);
      stream.next(m.checksum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PacketData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::packet_pkg::PacketData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::packet_pkg::PacketData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "face_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.face_name);
    s << indent << "face_confidence: ";
    Printer<float>::stream(s, indent + "  ", v.face_confidence);
    s << indent << "face_detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.face_detected);
    s << indent << "utc_time: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.utc_time);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "lat_direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.lat_direction);
    s << indent << "lon_direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.lon_direction);
    s << indent << "satellite_count: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.satellite_count);
    s << indent << "altitude: ";
    Printer<float>::stream(s, indent + "  ", v.altitude);
    s << indent << "speed_kph: ";
    Printer<float>::stream(s, indent + "  ", v.speed_kph);
    s << indent << "heading_true: ";
    Printer<float>::stream(s, indent + "  ", v.heading_true);
    s << indent << "heading_magnetic: ";
    Printer<float>::stream(s, indent + "  ", v.heading_magnetic);
    s << indent << "cpu_usage: ";
    Printer<float>::stream(s, indent + "  ", v.cpu_usage);
    s << indent << "memory_usage: ";
    Printer<float>::stream(s, indent + "  ", v.memory_usage);
    s << indent << "frame_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.frame_count);
    s << indent << "checksum: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.checksum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACKET_PKG_MESSAGE_PACKETDATA_H
