(cl:in-package packet_pkg-msg)
(cl:export '(HEADER-VAL
          HEADER
          FACE_NAME-VAL
          FACE_NAME
          FACE_CONFIDENCE-VAL
          FACE_CONFIDENCE
          FACE_DETECTED-VAL
          FACE_DETECTED
          UTC_TIME-VAL
          UTC_TIME
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          LAT_DIRECTION-VAL
          LAT_DIRECTION
          LON_DIRECTION-VAL
          LON_DIRECTION
          SATELLITE_COUNT-VAL
          SATELLITE_COUNT
          ALTITUDE-VAL
          ALTITUDE
          SPEED_KPH-VAL
          SPEED_KPH
          HEADING_TRUE-VAL
          HEADING_TRUE
          HEADING_MAGNETIC-VAL
          HEADING_MAGNETIC
          CPU_USAGE-VAL
          CPU_USAGE
          MEMORY_USAGE-VAL
          MEMORY_USAGE
          FRAME_COUNT-VAL
          FRAME_COUNT
          CHECKSUM-VAL
          CHECKSUM
))